# Version of Docker-compose
version: '3.9'
services:
  # Add the backend service
  backend:
  # Location to the backend dockerfile
    build: 
      context: ./backend
        # Name of the dockerfile
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      # Host port:Container port
      - '3000:3000'
    volumes:
      # Bind-mounts configuration
      - ./node:/app
      # Ignoring any changes made in the "node_modules" folder
      - ./app/node_modules
  react:
    # Location to the frontend dockerfile
      build: 
        context: ./frontend
          # Name of the dockerfile
        dockerfile: Dockerfile
      container_name: frontend-container
      ports:
      # Host port:Container port
        - '5173:5173'
      stdin_open: true