# Version of Docker-compose
version: '3.9'
services:
  frontend:
      build: 
        context: ./frontend
        dockerfile: Dockerfile
      container_name: aeriform-fe-container
      ports:
        - '5173:5173'
      stdin_open: true
      depends_on:
        - backend
        

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: aeriform-be-container
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/aeriform
    depends_on:
      - mongo


  mongo:
    container_name: aeriform-mongo-container
    image: mongo:latest
    ports:
      - 27017:27017
  
    