service: serverless
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-2
  timeout: 30

functions:
  studios:
    handler: studios.router
    events:
      - httpApi:
          method: '*'
          path: /studios
  users:
    handler: users.router
    events:
      - httpApi:
          method: '*'
          path: /users

