const cities = [
  { label: "Birmingham", type: "City" },
  { label: "Coventry", type: "City" },
  { label: "London", type: "City" },
  { label: "Manchester", type: "City" },
  { label: "Walsall", type: "City" },
  { label: "Wolverhampton", type: "City" },
];
// const cityList = {
//   cities: [
//     "bath",
//     "bradford",
//     "brighton",
//     "bristol",
//     "cambridge",
//     "cantebury",
//     "carlise",
//     "chelmsform",
//     "chester",
//     "chichester",
//     "colchester",
//     "coventry",
//     "derby",
//     "doncaster",
//     "durham",
//     "exeter",
//     "gloucster",
//     "hereford",
//     "kingston upon hull",
//     "lancaster",
//     "leeds",
//     "leicester",
//     "lichfield",
//     "lincoln",
//     "liverpool",
//     "london",
//     "manchester",
//     "milton keynes",
//     "newcastle upon tyne",
//     "norwich",
//     "nottingham",
//     "oxford",
//     "peterborough",
//     "plymouth",
//     "portsmouth",
//     "preston",
//     "salford",
//     "salisbury",
//     "sheffield",
//     "southhamptom",
//     "southend on sea",
//     "st albans",
//     "stoke on trent",
//     "sunderland",
//     "wakefield",
//     "westminster",
//     "winchester",
//     "wolverhampton",
//     "worcester",
//     "york",
//   ],
// };

export default cities;
