import CitiesRegion from '../types/cities-regions.ts';

const cities: CitiesRegion[] = [
    // { label: 'Bath', type: 'City' },
    { label: 'Birmingham', type: 'City' },
    // { label: 'Bradford', type: 'City' },
    // { label: 'Brighton', type: 'City' },
    // { label: 'Bristol', type: 'City' },
    // { label: 'Cambridge', type: 'City' },
    // { label: 'Cantebury', type: 'City' },
    // { label: 'Carlise', type: 'City' },
    // { label: 'Chelmsform', type: 'City' },
    // { label: 'Chester', type: 'City' },
    // { label: 'Chichester', type: 'City' },
    // { label: 'Colchester', type: 'City' },
    { label: 'Coventry', type: 'City' },
    // { label: 'Derby', type: 'City' },
    // { label: 'Doncaster', type: 'City' },
    { label: 'Dudley', type: 'City' },
    // { label: 'Durham', type: 'City' },
    // { label: 'Exeter', type: 'City' },
    // { label: 'Gloucster', type: 'City' },
    // { label: 'Hereford', type: 'City' },
    // { label: 'Kingston upon Hull', type: 'City' },
    // { label: 'Lancaster', type: 'City' },
    // { label: 'Leeds', type: 'City' },
    // { label: 'Leicester', type: 'City' },
    // { label: 'Lichfield', type: 'City' },
    // { label: 'Lincoln', type: 'City' },
    // { label: 'Liverpool', type: 'City' },
    // { label: 'London', type: 'City' },
    // { label: 'Manchester', type: 'City' },
    // { label: 'Milton Keynes', type: 'City' },
    // { label: 'Newcastle upon tyne', type: 'City' },
    // { label: 'Norwich', type: 'City' },
    // { label: 'Nottingham', type: 'City' },
    // { label: 'Oxford', type: 'City' },
    // { label: 'Peterborough', type: 'City' },
    // { label: 'Plymouth', type: 'City' },
    // { label: 'Portsmouth', type: 'City' },
    // { label: 'Preston', type: 'City' },
    // { label: 'Salford', type: 'City' },
    // { label: 'Salisbury', type: 'City' },
    { label: 'Sandwell', type: 'City' },
    // { label: 'Sheffield', type: 'City' },
    { label: 'Solihull', type: 'City' },
    // { label: 'Southhamptom', type: 'City' },
    // { label: 'Southend on Sea', type: 'City' },
    // { label: 'St Albans', type: 'City' },
    // { label: 'Stoke on Trent', type: 'City' },
    // { label: 'Sunderland', type: 'City' },
    // { label: 'Wakefield', type: 'City' },
    { label: 'Walsall', type: 'City' },
    // { label: 'Westminster', type: 'City' },
    // { label: 'Winchester', type: 'City' },
    { label: 'Wolverhampton', type: 'City' }
    // { label: 'Worcester', type: 'City' },
    // { label: 'York', type: 'City' }
];

export default cities;
